apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app 
  name: node-app 
spec:
  type: NodePort
  ports:
    - port: 3067
      targetPort: 3067
      protocol: TCP
  selector:
    app: node-app

